FROM ubuntu:22.04

USER root
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        bash \
        ca-certificates \
        curl \
        git \
	sudo

RUN apt-get clean 

RUN useradd vf-user \
        --create-home \
        --shell=/bin/bash \
        --uid=1000 \
        --user-group && \
    echo "vf-user ALL=(ALL) NOPASSWD:ALL" >>/etc/sudoers.d/nopasswd

ENV LANG en_US.UTF-8
USER vf-user
