# Adds a "Desktop" app to this workspace in the vf-user dashboard
apps:
  - name: Desktop
    scheme: http
    port: 6081
    # Working directory
    working-directory: /home/vf-user
    # File path to icon used in application launcher
    icon-path: /vf-user/apps/desktop.png
    # VNC server will be started by default in this image
    command: supervisorctl
    # Array of arguments for command
    args: ["start", "vncserver"]
    health-check:
      exec:
        command: "supervisorctl"
        args: ["status", "vncserver"]
      http:
        scheme: "http"
        path: "/"
        port: 6081
